{% set name = "rpy2-arrow" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d4e2cbdce75c00b67731c257883457ebe328aa8aec4ef5c39d83f3c64172379

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - rpy2 >=3.4
    - pyarrow >=5
    - r-arrow >=5

test:
  imports:
    - rpy2_arrow.pyarrow_rarrow
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rpy2/rpy2-arrow
  summary: Share Apache Arrow datasets between Python and R.
  description: |
    `rpy2-arrow` allows you to share the same arrow datasets between Python and
    R without copying the data. This takes advantage of the Arrow C-API.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewwardrop
